---
- name: Synchronize `runit` user services folder
  ansible.posix.synchronize:
    src: ../../../assets/runit-userservices/
    dest: "/home/{{ user.name }}/.local/runit/sv"
    recursive: true

- name: Ensure `run` folder exists for runit user services
  ansible.builtin.file:
    path: "/home/{{ user.name }}/.local/runit/run/"
    state: directory
    mode: 0755

# - name: Link runit user services from `sv` to `run` folder
#   ansible.builtin.file:
#     src: ~/.local/runit/sv/*
#     dest: ~/.local/runit/run/
#     state: link
