---
- name: Create the `aur_builder` user
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel
    state: present

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-ansible-aur_builder-pacman-nopass
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: true
    validate: "visudo -cf %s"

- name: Allow the `aur_builder` user to run `doas pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/doas.conf
    line: "permit nopass aur_builder cmd pacman"
    create: true

- name: Set `rustup` default version
  ansible.builtin.command: rustup default stable
  become: true
  become_user: aur_builder

- name: Install `paru` using makepkg if it isn't installed already
  kewlfft.aur.aur:
    name: paru-bin
    use: makepkg
    state: present
  become: true
  become_user: aur_builder

- name: Enable `BottomUp` listing in `paru`
  become: true
  ansible.builtin.blockinfile:
    path: /etc/paru.conf
    block: |
      [options]
      BottomUp
    marker: "# {mark} ANSIBLE MANAGED BLOCK for BottomUp"
    state: present

- name: Use `doas` instead of `sudo` in paru
  ansible.builtin.blockinfile:
    path: /etc/paru.conf
    block: |
      [bin]
      Sudo = doas
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    state: present
  become: true
